language: python
branches:
  only:
   - main
   - master

python:
 - "3.5"

before_install:
  - chmod -R +x scripts/test.sh

install:
 - pip install -q -r requirements/test.txt

script:
 - pycodestyle .
 - scripts/test.sh